force-app/main/default/objects/Account/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>UK</fullName>
            </value>
            <value>
                <fullName>Netherlands</fullName>
            </value>
            <value>
                <fullName>Germany</fullName>
            </value>
            <value>
                <fullName>France</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Services__c.field-meta.xml
<CustomField>
    <fullName>Services__c</fullName>
    <label>Services</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Service1</fullName>
            </value>
            <value>
                <fullName>Service2</fullName>
            </value>
            <value>
                <fullName>Service3</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/directoryResultController.cls
/* *************************
  Controller for directoryResults page

************************* */
public class directoryResultController {

    public Account record;
    
    public directoryResultController(ApexPages.StandardController cont) {
        record = [Select Id, Name, Services__c, Location__c From Account Where Id = :cont.getId()];
    }
    
    public list<string> getServices() {
       if(record.Services__c != null) return record.Services__c.split(';');       
       return new list<string>{};
    }
    
}