force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <displayFormat>P-{00000}</displayFormat>
        <label>Payment Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment__c/fields/Payment_Amount__c.field-meta.xml
<CustomField>
    <fullName>Payment_Amount__c</fullName>
    <label>Payment Amount</label>
    <precision>5</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/PaymentControllerExtension.cls
public class PaymentControllerExtension {
	    public String Page {get; set;}
	    public String OpenPageURL {get; set;}    
        String instId = Label.worldpayID; 
    private final Payment__c paym;
 	    public PaymentControllerExtension(ApexPages.StandardController stdController) {
	        this.paym = (Payment__c)stdController.getRecord();

	    }
       // public String amount = String.valueOf(paym.Payment_Amount__c);    
	    public PageReference redirect()

	    {
	        if(Page == 'pay')
	        {
	            OpenPageURL = 'https://secure-test.worldpay.com/wcc/purchase?instId=' + instId + '&cartId='+ paym.Name +'&amount=' + String.valueOf(paym.Payment_Amount__c) + '&currency=GBP&desc=Broker+Test&testMode=100' ;
	        	system.debug(OpenPageURL);
            }
	        return null;
	    }    
}